name: ynr
favicon: null
layout_spectrum: 0.9135630598757416
typography_spectrum: 0.6254835021682084
title: ynr
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#738b97'
    - '#000000'
    - '#bbc5c6'
    - '#4b5520'
  brandStrength: 0.5232603510376066
  lightness: 0.6019563798326999
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
